import Joi from "joi";

export const envJoiSchema: Joi.ObjectSchema = Joi.object({
  PORT: Joi.number().default(8000),
  NODE_ENVIRONMENT: Joi.string().default("development"),
  MONGO_DB_URL: Joi.string().default("mongodb://localhost:27017/boilerplate"),
  MONGO_DB_USERNAME: Joi.string().default(""),
  MONGO_DB_PASSWORD: Joi.string().default(""),
  MONGO_DB_SERVER: Joi.string().default(""),
  MONGO_DB_DATABASE: Joi.string().default(""),
  MONGO_DB_ENVIRONMENT: Joi.string().default(""),
  PASSWORD_SALT: Joi.number().default(10),
  JWT_ACCESS_TOKEN_SECRET_KEY: Joi.string().default("sfsd#4vg%5"),
  JWT_ACCESS_TOKEN_SECRET_KEY_EXPIRY: Joi.string().default("1"),
  JWT_REFRESH_TOKEN_SECRET_KEY: Joi.string().default("3"),
  JWT_REFRESH_TOKEN_SECRET_KEY_EXPIRY: Joi.string().default("gsf34%66"),
  EMAIL_SERVICE: Joi.string().default(""),
  EMAIL_FROM: Joi.string().default(""),
  EMAIL_USERNAME: Joi.string().default(""),
  EMAIL_PASSWORD: Joi.string().default(""),
  ENCRYPTION_KEY: Joi.string().default("a72de974337ed"),
  ISSUER: Joi.string().default("http://localhost:8000"),
  AUDIENCE: Joi.string().default("http://localhost:83000"),
  CLOUDINARY_NAME: Joi.string().default(""),
  CLOUDINARY_API_KEY: Joi.string().default(""),
  CLOUDINARY_API_SECRET: Joi.string().default(""),
  CLOUDINARY_STORAGE_FOLDER: Joi.string().default(""),
  STORAGE_DIRECTORY: Joi.string().default(""),
});
