const Message = {
  HELLO_WORLD: "Hello World!",
  INVALID_ENDPOINT: "Can't find <URL> on the server",
  INVALID_JWT: "Invalid JWT token",
  RATE_LIMIT: "You have exceeded the rate limit.",
  SOMETHING_WENT_WRONG: "Something went wrong",
  USER_REGISTER: "User is registered successfully",
  USER_LOGGED_IN: "User logged in successfully",
  USER_NOT_EXISTS: "User does not exists",
  USER_ALREADY_EXISTS: "User already exists",
  UNAUTHORIZED: "Email or password are incorrect",
  FORBIDDEN: "You don't have an access",
  EMAIL_ALREADY_VERIFIED: "Email verification already done",
  EMAIL_VERIFICATION: "Email verification successful",
  EMAIL_VERIFICATION_RESEND: "Resend email verification successful",
  VERIFICATION_TOKEN_EXPIRED: "Verification token is expired",
  RESET_PASSWORD_EMAIL: "Reset password email sent successfully",
  SET_NEW_PASSWORD: "Set new password successfully",
  RESEND_RESET_PASSWORD_REQUEST: "Resend reset password request email",
  SET_NEW_PASSWORD_TOKEN_EXPIRED: "Set new password token is expired",
  INCORRECT_SET_NEW_PASSWORD_TOKEN: "Set new password token is incorrect",
  UNAUTHORIZED_TOKEN: "Unauthorized user",
  GET_PROFILE: "Get user profile details",
  UPDATE_PROFILE: "User profile updated successfully",
  PROFILE_PICTURE_UPLOADED: "Profile picture uploaded successful",
  CHANGE_PASSWORD: "User password changed successfully",
  LOG_OUT: "User logged out successfully",
  GET_ALL_USERS: "Users are retrieved successfully",
  GET_USER: "User is retrieved successfully",
  LIMIT_REQUIRED: "Limit param must be positive number",
  ONLY_IMAGES_ALLOWED: "Only image files are allowed",
  UPDATE_USER_ROLE: "User role updated successfully",
  CAN_NOT_CHANGE_ROLE: "User can not change own user role",
  NOT_MATCH_CURRENT_PASSWORD:
    "Provided current password does not match with user's current password",
  SAME_NEW_CURRENT_PASSWORD:
    "New password could not be same as user's current password",
};

export default Message;
